config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "users/registrations"}

  get 'home/index'

  resources :users, except: [:destroy, :new] do
    resources :memberships, except: :index, controller: 'users/memberships'
    resources :signatures, except: %i[:destroy, :edit, :update], controller: 'users/signatures'
  end

  # TODO: this should go away, we don't need a whole resource, module and controller just to modify a field on a record
  # of a type that already has those things
  scope module: :users do
    resources :deactivate, only: :create
  end

  resources :email_templates

  resources :fee_types

  resources :agreements do
    resources :versions, controller: 'agreements/versions'
  end


  resources :locations
  resources :membership_types, except: :show

  resources :carriers do
    resources :loans, only: [:create, :edit, :new, :update], module: :carriers
  end

  get '/loan_listing', to: 'loan_listing#index', as: :loan_listing

  resources :photos, only: :destroy

  constraints subdomain: %w(admin) do
    root :to => "organizations#index", :as=> :subdomain_root
    resources :categories
    resources :organizations
  end

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  authenticate :user, lambda { |u| u.organization.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'carriers#index'

end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  acts_as_tenant(:organization)
  include User::FilterImpl

  has_person_name

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
  validates :first_name, :last_name, :street_address, :city,
            :state, :postal_code, :phone_number, presence: true

  # we can remove these below and reimplement :validateable
  # if they ever merge: https://github.com/heartcombo/devise/pull/5094
  validates_presence_of :email
  validates_uniqueness_of :email, scope: :organization_id
  validates_format_of :email, with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i, allow_blank: true,
                              if: :email_changed?
  validates_format_of :phone_number, with: /\A\d{10}\z/, message: 'must be 10 digits.'

  validates_format_of :postal_code, with: /\A\d{5}\z/, message: 'should be a valid 5 digit number.'
  validates_presence_of :password, if: :password_required?
  validates_confirmation_of :password, if: :password_required?
  validates_length_of :password, within: 8..100, allow_blank: true

  before_validation :scrub_phone_number

  has_many :loans, foreign_key: 'borrower_id', dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :signatures, dependent: :destroy

  enum role: %i[admin volunteer user]

  scope :admins, -> { where(role: admin) }
  scope :volunteers, -> { where(role: :volunteer) }

  scope :with_current_membership, lambda {
    t = Time.zone.today
    distinct.left_joins(:memberships).where('memberships.expiration >= ? and '\
                                        'memberships.effective <= ? and '\
                                        'memberships.blocked = ?', t, t, false)
  }

  scope :with_expired_membership, lambda {
    distinct.left_joins(:memberships).where('memberships.expiration < ?', Time.zone.today)
  }

  scope :without_membership, lambda {
    left_outer_joins(:memberships).where(memberships: { id: nil })
  }

  # see https://github.com/heartcombo/devise/wiki/How-to:-Scope-login-to-subdomain
  def self.find_for_authentication(warden_conditions)
    where(email: warden_conditions[:email], organization_id: warden_conditions[:organization_id]).first
  end

  def self.to_csv
    attributes = %w[first_name last_name email phone_number created_at]

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |user|
        csv << user.attributes.values_at(*attributes)
      end
    end
  end

  def active_signatures
    signatures.active
  end

  def current_membership
    today = Time.zone.today
    membership = memberships.where(
      'expiration >= ? AND effective <= ? and blocked= ?', today, today, false
    ).order(expiration: :desc).first
    return if membership.nil?

    membership
  end

  def latest_membership
    memberships.order(expiration: :desc).first
  end

  def loans_available_to_member?
    return unless current_membership

    allowed_loans = current_membership.membership_type.number_of_items
    outstanding_loans = loans&.count

    allowed_loans > outstanding_loans
  end

  def send_welcome_email
    WelcomeMailer.welcome_email(id).deliver_later
  end

  def name_with_membership
    membership = memberships.last
    return name.full if membership.nil?

    s = "#{name.full} - #{membership.membership_type.short_name}"
    s += ' (Expired)' if membership.expired?
    s
  end

  def unsigned_agreements
    AgreementVersion.joins(:agreement).active
                    .where('agreements.organization_id = ?', organization_id)
                    .where.not(id: active_signatures.pluck(:agreement_version_id))
  end

  private

  def password_required?
    !persisted? || !password.nil? || !password_confirmation.nil?
  end

  def scrub_phone_number
    self.phone_number = phone_number&.delete('^0-9')
  end
end

app/models/user/filter_impl.rb
# frozen_string_literal: true

class User
  module FilterImpl
    extend ActiveSupport::Concern

    included do
      scope :search_name, lambda(&method(:name_search))
      scope :search_email, ->(email) { where('email ilike ?', "%#{email}%") }
      scope :with_created_after, ->(date) { where('users.created_at > ?', parsed_created_after(date)) }
      scope :with_role, ->(role) { where(role: role) }

      scope :with_membership_status, lambda { |status|
        case status
        when 'Current'
          with_current_membership
        when 'Expired'
          with_expired_membership.where.not(id: with_current_membership)
        when 'None'
          without_membership
        end
      }

      filterrific(available_filters: %i[
                    search_name
                    search_email
                    with_created_after
                    with_role
                    with_membership_status
                  ])
    end

    def self.options_for_membership_filter
      %w[Current Expired None]
    end

    def self.options_for_role_filter
      User.roles.sort.map { |r| [r.first.titleize, r.second] }
    end
  end

  def self.name_search(query)
    splitted = query.strip.split(' ')
    if splitted.length > 1
      User.default_scoped.where('first_name ilike ? and last_name ilike ?', "%#{splitted.first}%", "%#{splitted.last}%")
    else
      User.default_scoped.where('first_name ilike ? or last_name ilike ?', "%#{splitted.first}%", "%#{splitted.first}%")
    end
  end

  def self.parsed_created_after(date)
    Date.parse(date).beginning_of_day
  rescue Date::Error
    (Date.today - 100.years)
  end
end

app/controllers/users/deactivate_controller.rb
# frozen_string_literal: true

module Users
  class DeactivateController < ApplicationController
    def create
      user = User.find(params[:id])
      user.deactivated? ? user.activate : user.deactivate

      redirect_back(fallback_location: users_path)
    end
  end
end

app/controllers/users/memberships_controller.rb
# frozen_string_literal: true

module Users
  class MembershipsController < ApplicationController
    before_action :set_user

    respond_to :html, :json

    def create
      @membership = authorize @user.memberships.new(membership_params)
      if @membership.save
        redirect_to user_path(@user), notice: 'Membership successfully created.'
      else
        respond_modal_with @membership
      end
    end

    def destroy
      @membership = authorize @user.memberships.find(params[:id])
      flash[:notice] = 'Membership successfully removed.' if @membership.destroy
      redirect_to user_path(@user)
    end

    def edit
      @membership = authorize @user.memberships.find(params[:id])

      respond_modal_with @membership
    end

    def new
      @membership = authorize @user.memberships.build
      respond_modal_with @membership
    end

    def update
      @membership = authorize @user.memberships.find(params[:id])
      if @membership.update(membership_params)
        redirect_to user_path(@user), notice: 'Membership successfully updated.'
      else
        respond_modal_with @membership
      end
    end

    private

    def membership_params
      params.require(:membership).permit(:id, :membership_type_id, :blocked, :effective, :expiration)
    end

    def set_user
      @user = User.find(params[:user_id])
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    skip_before_action :require_no_authentication, only: %i[new create]

    def create
      super
      return unless resource.persisted?

      set_flash_message!(:notice, current_user == resource ? :signed_up : :signed_up_by_user)
      resource.send_welcome_email
    end

    private

    # so as not to sign in new user when user created by volunteer
    def sign_up(resource_name, resource)
      super unless current_user
    end

    def sign_up_params
      params.require(:user).permit(:email, :password, :password_confirmation,
                                   :first_name, :last_name, :street_address,
                                   :street_address_second, :city, :state,
                                   :postal_code, :phone_number)
    end

    def account_update_params
      params.require(:user).permit(:email, :password, :password_confirmation,
                                   :current_password, :first_name, :last_name,
                                   :street_address, :street_address_second,
                                   :city, :state, :postal_code, :phone_number)
    end
  end
end

app/controllers/users/signatures_controller.rb
# frozen_string_literal: true

module Users
  class SignaturesController < ApplicationController
    include UserScoped

    def create
      @signature = @user.signatures.new(signature_params.merge(signed_at: Time.zone.now))
      if @signature.save
        redirect_to user_signatures_path(@user), notice: 'Agreement successfully signed.'
      else
        flash[:error] = @signature.errors.full_messages
        redirect_to(new_user_signature_path(@user, agreement_version_id: params[:agreement_version_id]))
      end
    end

    def index
      @signatures = @user.active_signatures
      @unsigned_agreements = @user.unsigned_agreements
    end

    def new
      @signature = @user.signatures.build(agreement_version_id: params[:agreement_version_id])
    end

    private

    def signature_params
      params.require(:signature).permit(:id, :agreement_version_id, :signature)
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update show]

  def index
    init_filters || return
    @users = authorize @filterrific.find.page(params[:page])

    respond_to do |format|
      format.html
      format.js
      format.csv { send_data @users.to_csv, filename: "users-#{Date.today}.csv" }
    end
  end

  def edit
    authorize @user
  end

  def update
    authorize @user
    if @user.update(permitted_attributes(@user))
      redirect_to users_url, notice: 'User was successfully updated.'
    else
      render 'edit'
    end
  end

  def show
    authorize @user

    @loans = @user.loans
    @memberships = { history: @user.memberships.order(expiration: :desc), current: [@user.current_membership].compact }
  end

  private

  def init_filters
    @filterrific = initialize_filterrific(
      User.includes(:memberships), params[:filterrific],
      select_options: {
        with_role: User::FilterImpl.options_for_role_filter,
        with_membership_status: User::FilterImpl.options_for_membership_filter
      }
    )
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def user_initials(user)
    user.name.initials
  end

  def user_roles_select
    User.roles.keys.map { |role| [role.humanize, role] }
  end

  def membership_status(user)
    return 'None' if user.memberships.empty?

    latest = user.latest_membership
    return 'Expired' if latest.expired?

    latest.blocked? ? 'Blocked' : 'Current'
  end
end

app/views/users/_filter_form.html.erb
<%= form_for_filterrific filterrific do |f| %>
  <div class="row">
    <div class="col">
      <label>Name</label>
      <%= f.text_field(
              :search_name,
              class: 'filterrific-periodically-observed form-control'
          ) %>
    </div>
    <div class="col">
      <label>Email</label>
      <%= f.text_field(
              :search_email,
              class: 'filterrific-periodically-observed form-control'
          ) %>
    </div>
    <div class="col">
      <label>Joined After</label>
      <%= f.date_field(
              :with_created_after,
              class: 'filterrific-periodically-observed form-control'
          ) %>
    </div>
    <div class="col">
      <label>Role</label>
      <%= f.select(
              :with_role,
              filterrific.select_options[:with_role],
              { include_blank: "Any" },
              class: 'form-control'
          ) %>
    </div>
    <div class="col">
      <label>Membership Status</label>
      <%= f.select(
              :with_membership_status,
              filterrific.select_options[:with_membership_status],
              { include_blank: "Any" },
              class: 'form-control'
          ) %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= link_to "Reset Filters", reset_filterrific_url, class: 'btn btn-secondary btn-sm' %>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with model: user, local: true do |form| %>
  <%= form_errors @user %>

  <div class="form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :role %>
    <%= form.select :role, user_roles_select, {}, { class: "form-control", disabled: !current_user.admin? } %>
  </div>

  <div class="form-group">
    <%= form.label :street_address %>
    <%= form.text_field :street_address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :street_address_second %>
    <%= form.text_field :street_address_second , class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :city %>
    <%= form.text_field :city, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :state %>
    <%= form.text_field :state, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :postal_code %>
    <%= form.text_field :postal_code, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :phone_number, 'Phone number (xxx-xxx-xxxx)' %>
    <%= form.phone_field :phone_number, class: "form-control", value: number_to_phone(form.object.phone_number) %>
  </div>

  <%= form.submit class: "btn btn-primary" %>
<% end %>

app/views/users/_list.html.erb
<%= render 'shared/pagination', items: users %>
<table class="table" data-toggle="table">
  <thead class="thead-light">
    <tr>
      <th data-sortable="true">Name</th>
      <th data-sortable="true">Email</th>
      <th>Phone</th>
      <th>Join Date</th>
      <th data-sortable="true">Role</th>
      <th data-sortable="true">Status</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% if users.empty? %>
      <tr>
        <td colspan="100%">No users to show</td>
      </tr>
    <% else %>
      <% users.each do |user| %>
        <tr>
          <td><%= link_to user.name, user_path(user) %></td>
          <td><%= user.email %></td>
          <td><%= number_to_phone(user.phone_number) %></td>
          <td><%= I18n.localize user.created_at.to_date %></td>
          <td><%= user.role.humanize %></td>
          <td><%= membership_status(user) %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<% unless users.empty? %>
  <div class="mt-4">
    <%= button_to "Export to CSV", "/users.csv", :method => :get %>
  </div>
<% end %>

app/views/users/_loan_history.html.erb
<header class="card-header d-flex align-items-center">
  <h3>Loan History</h3>
</header>
<% if loans.empty? %>
  <div class="p-3">No loans found for this user.</div>
<% else %>
  <table data-toggle="table">
    <thead class="thead-light">
    <tr>
      <th>Loan</th>
      <th>Carrier</th>
      <th>Checked Out Date</th>
      <th>Checkout Volunteer</th>
      <th>Due Date</th>
      <th>Returned Date</th>
      <th>Checkin Volunter</th>
    </tr>
    </thead>

    <tbody>
    <% loans.each do |loan| %>
      <tr>
        <td><%= link_to 'Edit', edit_carrier_loan_path(loan.carrier, loan), class: 'btn btn-primary btn-sm', data: {modal: true} %></td>
        <td><%= link_to loan.carrier.name, carrier_path(loan.carrier.id) %></td>
        <td><%= loan.created_at.to_date %></td>
        <% volunteer = loan.checkout_volunteer %>
        <td><%= volunteer.first_name + " " + volunteer.last_name %></td>
        <td><%= loan.due_date %></td>
        <td><%= loan.returned_on %></td>
        <% volunteer = loan.checkin_volunteer %>
        <td><%= volunteer.first_name + " " + volunteer.last_name if volunteer %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/users/_memberships.html.erb
<header class="card-header d-flex align-items-center">
  <h3>Memberships</h3>
</header>
<% if memberships[:history].empty? %>
  <div class="p-3">No memberships found for this user.</div>
<% else %>
  <div class="container memberships-list">
    <ul class="nav nav-tabs" id="membership-tabs" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="current-membership-tab" data-toggle="tab" href="#current-membership-content" role="tab" aria-controls="current"
           aria-selected="true">Current</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="membership-history-tab" data-toggle="tab" href="#membership-history-content" role="tab" aria-controls="history"
           aria-selected="false">History</a>
      </li>
    </ul>
    <div class="tab-content" id="membership-content">
      <div class="tab-pane fade show active" id="current-membership-content" role="tabpanel" aria-labelledby="home-tab">
        <%= render partial: "memberships_table", locals: { memberships: memberships[:current], current: nil } %>
      </div>
      <div class="tab-pane fade" id="membership-history-content" role="tabpanel" aria-labelledby="profile-tab">
        <%= render partial: "memberships_table", locals: { memberships: memberships[:history], current: memberships[:current].first } %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_memberships_table.html.erb
<table data-toggle="table">
  <thead class="thead-light">
  <tr>
    <th>Type</th>
    <th>Effective</th>
    <th>Expiration</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
    <% if memberships.empty? %>
      <tr><td colspan="100%">No memberships</td></tr>
    <% else %>
      <% memberships.each do |membership| %>
        <% class_name = (membership == current) ? "current-membership" : "" %>
        <tr class='<%= class_name %>'>
          <td><%= membership.membership_type.name %></td>
          <td><%= membership.effective %></td>
          <td><%= membership.expiration %></td>
          <td><%= link_to 'Edit', edit_user_membership_path(membership.user, membership), class: 'btn btn-primary btn-sm', data: {modal: true} %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class="col-md-6 card px-0">
  <div class="card-header"><h3>Edit User</h3></div>
  <div class="card-body">
    <%= render 'form', user: @user %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users</h1>
<div class="card">
  <div class="card filter-card">
    <div class="card-header">Filters</div>
    <div class="card-body">
      <%= render partial: 'filter_form', locals: { filterrific: @filterrific } %>
    </div>
    <div id="filterrific_results">
      <%= render partial: "list", locals: { users: @users } %>
    </div>
  </div>
</div>

app/views/users/index.js.erb
<% js = escape_javascript(
  render(partial: 'list', locals: { users: @users })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/users/show.html.erb
<h1> <%= @user.name %></h1>

<dl class="row mt-5">
  <dt class="col-sm-2 text-md-right">Email address:</dt>
  <dd class="col-sm-10"><%= @user.email %><br></dd>
  <dt class="col-sm-2 text-md-right">Phone number:</dt>
  <dd class="col-sm-10"><%= number_to_phone(@user.phone_number) %><br></dd>
  <dt class="col-sm-2 text-md-right">Joined on:</dt>
  <dd class="col-sm-10"><%= @user.created_at %><br></dd>
  <dt class="col-sm-2 text-md-right">Role:</dt>
  <dd class="col-sm-10"><%= @user.role.humanize %><br></dd>
  <dt class="col-sm-2 text-md-right">Membership Status:</dt>
  <dd class="col-sm-10"><%= membership_status(@user) %></dd>
</dl>

<div><%= link_to 'Edit User', edit_user_path(@user), class: "btn btn-primary btn-sm" %>
  <% link_text = (@memberships[:history].size > 0) ? "Renew Membership" : "Add Membership" %>
  <%= link_to link_text, new_user_membership_path(@user), class: "btn btn-primary btn-sm", data: { modal: true } %>
</div>

<div class="card mt-2">
  <%= render partial: 'memberships', locals: { memberships: @memberships} %>
</div>

<div class="card mt-4">
  <%= render partial: 'loan_history', locals: { loans: @loans} %>
</div>