config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "users/registrations"}

  get 'home/index'

  resources :users, except: [:destroy, :new] do
    resources :memberships, except: :index, controller: 'users/memberships'
    resources :signatures, except: %i[:destroy, :edit, :update], controller: 'users/signatures'
  end

  # TODO: this should go away, we don't need a whole resource, module and controller just to modify a field on a record
  # of a type that already has those things
  scope module: :users do
    resources :deactivate, only: :create
  end

  resources :email_templates

  resources :fee_types

  resources :agreements do
    resources :versions, controller: 'agreements/versions'
  end


  resources :locations
  resources :membership_types, except: :show

  resources :carriers do
    resources :loans, only: [:create, :edit, :new, :update], module: :carriers
  end

  get '/loan_listing', to: 'loan_listing#index', as: :loan_listing

  resources :photos, only: :destroy

  constraints subdomain: %w(admin) do
    root :to => "organizations#index", :as=> :subdomain_root
    resources :categories
    resources :organizations
  end

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  authenticate :user, lambda { |u| u.organization.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'carriers#index'

end

app/controllers/loan_listing_controller.rb
# frozen_string_literal: true

class LoanListingController < ApplicationController
  def index
    init_filters || return
    @loans = @filterrific.find.page(params[:page])
    authorize @loans

    respond_to do |format|
      format.html
      format.js
    end
  end

  private

  def init_filters
    @filterrific = initialize_filterrific(
      current_tenant.loans.includes(%i[carrier checkin_volunteer checkout_volunteer borrower]), params[:filterrific],
      select_options: {
        with_borrower_id: Loan::FilterImpl.options_for_borrower_filter,
        with_checkout_volunteer_id: Loan::FilterImpl.options_for_volunteer_filters,
        with_checkin_volunteer_id: Loan::FilterImpl.options_for_volunteer_filters,
        with_outstanding: Loan::FilterImpl.options_for_yes_no_filter,
        with_overdue: Loan::FilterImpl.options_for_yes_no_filter
      }
    )
  end
end

app/views/loan_listing/_filter_form.html.erb
<%= form_for_filterrific filterrific do |f| %>
  <div class="row">
    <div class="col">
      <%= f.label "Carrier model:" %>
      <%= f.text_field(
              :search_carrier,
              class: 'filterrific-periodically-observed form-control',
              placeholder: "Any"
      ) %>
    </div>
    <div class="col">
      <%= f.label "Due date before:" %>
      <%= f.date_field(
              :with_due_date_before,
              value: "hi",
              class: 'filterrific-periodically-observed form-control'
          ) %>
    </div>
    <div class="col">
      <%= f.label "Due date after:" %>
      <%= f.date_field(
              :with_due_date_after,
              class: 'filterrific-periodically-observed form-control'
          ) %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= f.select(
              :with_borrower_id,
              filterrific.select_options[:with_borrower_id],
              { include_blank: 'Loaned to' },

      ) %>
      <%= f.select(
              :with_checkout_volunteer_id,
              filterrific.select_options[:with_checkout_volunteer_id],
              { include_blank: 'Checkout Volunteer' },

      ) %>
      <%= f.select(
                :with_checkin_volunteer_id,
                filterrific.select_options[:with_checkin_volunteer_id],
                { include_blank: 'Checkin Volunteer' },
      ) %>
      <%= f.select(
              :with_outstanding,
              filterrific.select_options[:with_outstanding],
              { include_blank: 'Outstanding' },
      ) %>
      <%= f.select(
              :with_overdue,
              filterrific.select_options[:with_overdue],
              { include_blank: 'Overdue' }
      ) %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= link_to "Reset Filters", reset_filterrific_url, class: 'btn btn-secondary btn-sm' %>
    </div>
  </div>
<% end %>

app/views/loan_listing/_list.html.erb
<%= render 'shared/pagination', items: loans %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Borrower</th>
      <th scope="col">Carrier</th>
      <th scope="col">Due</th>
      <th scope="col">Returned</th>
      <th scope="col">Notes</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% if loans.empty? %>
      <tr>
        <td colspan="100%">No loans to show</td>
      </tr>
    <% else %>
      <% loans.each do |loan| %>
        <tr>
          <td><%= link_to loan.borrower.name, user_path(loan.borrower) %></td>
          <td><%= link_to loan.carrier.display_name, carrier_path(loan.carrier) %></td>
          <td><%= loan.due_date %></td>
          <td><%= loan.returned_on %></td>
          <td><%= truncate(loan.notes) %></td>
          <td><%= link_to "Edit", edit_carrier_loan_path(loan.carrier, loan), class: 'btn btn-primary btn-sm', data: { modal: true } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/loan_listing/index.html.erb
<div class="card">
  <header class="card-header d-flex align-items-center">
    <h3 class="mr-auto">Loan</h3>
  </header>
  <div class="card filter-card">
    <div class="card-header">Filters</div>
    <div class="card-body">
      <%= render partial: 'filter_form', locals: { filterrific: @filterrific } %>
    </div>
  </div>
  <section id="filterrific_results">
    <%= render 'list', loans: @loans %>
  </section>
</div>

app/views/loan_listing/index.js.erb
<% js = escape_javascript(
  render 'list', loans: @loans
) %>
$("#filterrific_results").html("<%= js %>");