config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "users/registrations"}

  get 'home/index'

  resources :users, except: [:destroy, :new] do
    resources :memberships, except: :index, controller: 'users/memberships'
    resources :signatures, except: %i[:destroy, :edit, :update], controller: 'users/signatures'
  end

  # TODO: this should go away, we don't need a whole resource, module and controller just to modify a field on a record
  # of a type that already has those things
  scope module: :users do
    resources :deactivate, only: :create
  end

  resources :email_templates

  resources :fee_types

  resources :agreements do
    resources :versions, controller: 'agreements/versions'
  end


  resources :locations
  resources :membership_types, except: :show

  resources :carriers do
    resources :loans, only: [:create, :edit, :new, :update], module: :carriers
  end

  get '/loan_listing', to: 'loan_listing#index', as: :loan_listing

  resources :photos, only: :destroy

  constraints subdomain: %w(admin) do
    root :to => "organizations#index", :as=> :subdomain_root
    resources :categories
    resources :organizations
  end

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  authenticate :user, lambda { |u| u.organization.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'carriers#index'

end

app/models/organization.rb
# frozen_string_literal: true

class Organization < ApplicationRecord
  # TODO: Some of these attributes would be best managed in an organization/settings model and controller so
  # that they can be managed by an organization admin (currently they can only be managed by an admin in the
  # admin organization)
  validates_presence_of :name, :reply_email, :subdomain
  validates_uniqueness_of :name, :subdomain, case_sensitive: false

  validates_format_of :phone, with: /\A\d{10}\z/, message: 'must be 10 digits.', allow_nil: true

  before_destroy :admin_indestructable

  validates :subdomain, subdomain: true

  before_validation :scrub_phone

  has_many :agreements, dependent: :destroy
  has_many :carriers, dependent: :destroy
  has_many :loans, through: :carriers
  has_many :fee_types, dependent: :destroy
  has_many :locations, dependent: :destroy
  has_many :users, dependent: :destroy
  has_many :membership_types, dependent: :destroy

  has_many :checkout_email_templates, dependent: :destroy
  has_many :reminder_email_templates, dependent: :destroy
  has_many :welcome_email_templates, dependent: :destroy

  scope :nonadmin, -> { where.not('subdomain = ?', 'admin') }

  def admin?
    subdomain == 'admin'
  end

  private

  def admin_indestructable
    errors.add(:base, 'Cannot delete admin organization.') if admin?
    throw(:abort) if errors.any?
  end

  def scrub_phone
    self.phone = phone&.delete('^0-9')
  end
end

app/controllers/organizations_controller.rb
# frozen_string_literal: true

class OrganizationsController < ApplicationController
  before_action :set_organization, only: %i[show edit update destroy]

  def index
    @organizations = Organization.order(:name)
  end

  def new
    @organization = Organization.new
  end

  # # GET /categories/1/edit
  # def edit
  # end
  #

  def create
    @organization = Organization.new(organization_params)

    if @organization.save
      redirect_to organization_url(@organization, subdomain: 'admin'),
                  notice: 'Organization was successfully created.'
    else
      render :new
    end
  end

  def update
    if @organization.update(organization_params)
      redirect_to organization_url(@organization, subdomain: 'admin'),
                  notice: 'Organization was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    destroyed = @organization.destroy

    redirect_to organizations_url(subdomain: 'admin'),
                alert: destroyed ? 'Organization was successfully destroyed.' : 'Could not destroy organization.'
  end

  private

  def set_organization
    @organization = Organization.find(params[:id])
  end

  def organization_params
    params.require(:organization).permit(:name, :subdomain, :email, :reply_email, :phone, :notes, :address,
                                         :city, :state, :zip)
  end
end

app/views/organizations/_form.html.erb
<%= form_with(model: organization, local: true) do |form| %>
  <%= form_errors organization %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :subdomain %>
    <%= form.text_field :subdomain, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :reply_email %>
    <%= form.text_field :reply_email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :city %>
    <%= form.text_field :city, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :state %>
    <%= form.text_field :state, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :notes %>
    <%= form.text_area :notes, class: "form-control" %>
  </div>

  <%= form.submit class: "btn btn-primary" %>
<% end %>

app/views/organizations/_organization.html.erb
<tr>
  <td>
    <%= link_to organization.name, organization %>
  </td>
  <td><%= organization.subdomain %></td>
  <td><%= organization.email %></td>
  <td><%= number_to_phone(organization.phone) %></td>
  <td class="table-actions">
    <%= link_to 'Edit', edit_organization_path(organization), class: 'btn btn-primary btn-sm' %> |
    <%= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'  %>
  </td>
</tr>

app/views/organizations/edit.html.erb
<div class="col-md-6 card px-0">
  <div class="card-header"><h3>Edit Organization</h3></div>
  <div class="card-body">
    <%= render 'form', organization: @organization %>

    <%= link_to 'Show', @organization %> |
    <%= link_to 'Back', organizations_path %>
  </div>
</div>

app/views/organizations/index.html.erb
<div class="card">
  <header class="card-header d-flex align-items-center">
    <h3 class="mr-auto">Organizations</h3>
    <%= link_to '+ New', new_organization_path, class: "btn btn-primary" %>
  </header>

  <section>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Subdomain</th>
          <th scope="col">email</th>
          <th scope="col">Phone</th>
        </tr>
      </thead>
      <tbody>
        <% @organizations.each do |organization| %>
          <%= render 'organization', organization: organization %>
        <% end %>
      </tbody>
    </table>
  </section>
</div>

app/views/organizations/new.html.erb
<div class="col-md-6 card px-0">
  <div class="card-header"><h3>New Organization</h3></div>
  <div class="card-body">
    <%= render 'form', organization: @organization %>
    <%= link_to 'Back', organizations_path %>
  </div>
</div>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<h1> <%= @organization.name %></h1>

<dl class="row mt-5">
  <dt class="col-sm-2 text-md-right">Name:</dt>
  <dd class="col-sm-10"><%= @organization.name %><br></dd>
  <dt class="col-sm-2 text-md-right">Subdomain:</dt>
  <dd class="col-sm-10"><%= @organization.subdomain %><br></dd>
  <dt class="col-sm-2 text-md-right">Email address:</dt>
  <dd class="col-sm-10"><%= @organization.email %><br></dd>
  <dt class="col-sm-2 text-md-right">Reply email address:</dt>
  <dd class="col-sm-10"><%= @organization.reply_email %><br></dd>
  <dt class="col-sm-2 text-md-right">Phone:</dt>
  <dd class="col-sm-10"><%= number_to_phone(@organization.phone) %><br></dd>
  <dt class="col-sm-2 text-md-right">Address:</dt>
  <dd class="col-sm-10"><%= @organization.address %><br></dd>
  <dt class="col-sm-2 text-md-right">City:</dt>
  <dd class="col-sm-10"><%= @organization.city %><br></dd>
  <dt class="col-sm-2 text-md-right">State:</dt>
  <dd class="col-sm-10"><%= @organization.state %><br></dd>
  <dt class="col-sm-2 text-md-right">Zip:</dt>
  <dd class="col-sm-10"><%= @organization.zip %><br></dd>
  <dt class="col-sm-2 text-md-right">Created:</dt>
  <dd class="col-sm-10"><%= @organization.created_at %><br></dd>
  <dt class="col-sm-2 text-md-right">Updated:</dt>
  <dd class="col-sm-10"><%= @organization.updated_at %></dd>
</dl>

<div><%= link_to 'Edit Organization', edit_organization_path(@organization), class: "btn btn-primary btn-sm" %>
</div>